### ISSUE TITLE
"cp-textures.sh" Appears to be missing

### ISSUE THREAD

**Issue by Annonymouse8** [innub/image-to-schematic#1]
I have had success running the program up until the step where it requests that you use the default block list or a custom one. The first time I ran the program, I selected the default (Option 1), after which the program stated it was missing cp-textures.sh and exited. The second time around, I located the block list file (in the colorizer folder) and selected the custom block list option. I entered the file path for the block list file, and got the same error message.
![Block list Error Attempt 1](https://user-images.githubusercontent.com/87604956/187035406-75ea930e-415c-47e1-81d5-985573ec8991.png)
![Block list Error Attempt 2](https://user-images.githubusercontent.com/87604956/187035409-478be14b-5730-4239-9487-67a27464a81e.png)
If there's any more detail I can provide to help troubleshooting, please say.

**Comment by akevinge** [comment]
@Annonymouse8 

In the .gitignore file, I added an entry that ignored the copy script as well! I'll fix it ASAP. Also, you might have issues compiling the program on Windows because g++-11 is required to built it. You can download the compiler for Windows [here](https://winlibs.com/). If the versions don't match just change "CPP = g++-11" in the Makefile of the colorize and mapper to whatever version of compiler you installed (it's at the very top of the file)

 Thanks for trying out my project! It means a lot to me. 
:heart:

**Comment by akevinge** [comment]
I'll try to run it on Windows today and get it working!

**Comment by Annonymouse8** [comment]
No, thank you for making this! It's the only locally-run 1.18.2 schematic creator I could find, the fact that there's just one person behind it's development is amazing.
